#! /bin/sh
set -e

#DEBHELPER#

case "$1" in
  remove|deconfigure|failed-upgrade)
    update-alternatives --remove x-cursor-theme \
        /usr/share/icons/PolarCursorTheme-Green/index.theme
  ;;
esac
